// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.
package envcfg

import (
	"errors"
	"strconv"
	"strings"
)

// Bool extracts and parses the variable provided according to the options provided.
// Available options:
// - "default" or Bool.Default
// - "optional" or Optional
func (c *Cfg) Bool(docOpts string, opts ...BoolOpt) (v bool) {
	s, err := newBoolSpec(docOpts, opts)
	if err != nil {
		if c.panic {
			panic(err)
		}
		c.addError(err)
		return
	}
	c.addDescription(s.describe())
	v, _ = c.evaluate(s).(bool)
	return
}

// BoolOpt modifies Bool variable configuration.
type BoolOpt interface {
	modify(s *spec)
	modifyBoolParser(p *boolParser)
}

var Bool = struct {
	Default func(bool) BoolOpt
}{
	Default: func(def bool) BoolOpt {
		return defaultOpt(def)
	},
}

type boolOptFunc func(p *boolParser)

func (f boolOptFunc) modifyBoolParser(p *boolParser) {
	f(p)
}

func (boolOptFunc) modify(*spec) {}

var _ BoolOpt = new(boolOptFunc)

func newBoolSpec(docOpts string, opts []BoolOpt) (*spec, error) {
	parsed, err := parse(docOpts)
	if err != nil {
		return nil, err
	}

	p := new(boolParser)
	s := &spec{
		parser:   p,
		typeName: "bool",
		name:     parsed.name,
		comment:  parsed.description,
	}

	for _, f := range parsed.fields {
		var (
			opt BoolOpt
			err error
		)
		switch strings.ToLower(f[0]) {
		case "default":
			val := f[1]
			opt = uniOptFunc(func(s *spec) {
				s.flags |= flagDefaultValString | flagDefaultVal
				s.defaultValS = val
			})
		case "optional":
			if f[1] != "" {
				err = errors.New("optional does not take any arguments")
			}
			opt = Optional
		}
		if err != nil {
			return nil, err
		}
		if opt == nil {
			return nil, errors.New("unknown")
		}
		opt.modify(s)
		opt.modifyBoolParser(p)
	}

	for _, opt := range opts {
		opt.modify(s)
		opt.modifyBoolParser(p)
	}

	if s.flags&flagDefaultValString > 0 {
		if s.defaultVal, err = p.parse(s.defaultValS); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type boolParser struct {
}

func (p *boolParser) parse(s string) (interface{}, error) {
	return strconv.ParseBool(
		s,
	)
}

func (p *boolParser) describe() interface{} {
	return struct{}{}
}
