// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.
package envcfg

import (
	"time"
)

type DurationOpt interface {
	modifyDurationParser(p *durationParser) error
}

// Duration extracts and parses the variable provided according to the options provided.
// Available options:
// - default
func (c *Cfg) Duration(docOpts string, opts ...DurationOpt) time.Duration {
	s, err := newDurationSpec(docOpts, opts)
	if err != nil {
		if c.panic {
			panic(err)
		}
		c.addError(err)
	}
	c.addDescription(s.describe())
	v, _ := c.evaluate(s).(time.Duration)
	return v
}

var Duration = struct {
	Default func(time.Duration) DurationOpt
}{
	Default: func(def time.Duration) DurationOpt {
		return defaultOpt(def)
	},
}

type durationOptFunc func(p *durationParser) error

func (f durationOptFunc) modifyDurationParser(p *durationParser) error {
	return f(p)
}

var _ DurationOpt = new(durationOptFunc)

func newDurationSpec(docOpts string, opts []DurationOpt) (*spec, error) {
	parsed, err := parseDocOpts(docOpts)
	if err != nil {
		return nil, err
	}

	os := make([]DurationOpt, 0, len(opts)+len(parsed))
	for _, p := range parsed {
		os = append(os, p)
	}

	p := new(durationParser)
	s := &spec{
		parser:   p,
		typeName: "time.Duration",
	}

	for _, opt := range append(os, opts...) {
		if opt, ok := opt.(interface{ modify(*spec) error }); ok {
			if err = opt.modify(s); err != nil {
				return nil, err
			}
			continue
		}
		if err := opt.modifyDurationParser(p); err != nil {
			return nil, err
		}
	}

	if s.flags&flagDefaultValString > 0 {
		if s.defaultVal, err = p.parse(s.defaultValS); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type durationParser struct {
}

func (p *durationParser) parse(s string) (interface{}, error) {
	return time.ParseDuration(
		s,
	)
}

func (p *durationParser) describe() interface{} {
	return struct{}{}
}
