package envcfg

// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.

import (
	"errors"
	"net"
	"strings"
)

// IP extracts and parses a net.IP variable using the options provided.
//
// The first argument must be a string with beginning with the variable name as expected in the process environment.
// Any other options -- none of which are required -- may either be specified in the remainder of the string or using
// the type-safe IPOpts.
//
// Available options:
// 		- "default" or IPDefault
// 		- "optional" or Optional
func (c *Cfg) IP(docOpts string, opts ...IPOpt) (v net.IP) {
	s, err := newIPSpec(docOpts, opts)
	if err != nil {
		if c.panic {
			panic(err)
		}
		c.addError(err)
		return
	}
	c.addDescription(s.describe())
	v, _ = c.evaluate(s).(net.IP)
	return
}

// IPOpt modifies IP variable configuration.
type IPOpt interface {
	modify(s *spec)
	modifyIPParser(p *ipParser)
}

// IPDefault specifies a default value for a IP variable.
func IPDefault(def net.IP) IPOpt {
	return defaultOpt(def)
}

type ipOptFunc func(p *ipParser)

func (f ipOptFunc) modifyIPParser(p *ipParser) {
	f(p)
}

func (ipOptFunc) modify(*spec) {}

var _ IPOpt = new(ipOptFunc)

func newIPSpec(docOpts string, opts []IPOpt) (*spec, error) {
	parsed, err := parse(docOpts)
	if err != nil {
		return nil, err
	}

	p := new(ipParser)
	s := &spec{
		parser:   p,
		typeName: "net.IP",
		name:     parsed.name,
		comment:  parsed.description,
	}

	for _, f := range parsed.fields {
		var (
			opt IPOpt
			err error
		)
		switch strings.ToLower(f[0]) {
		case "default":
			val := f[1]
			opt = uniOptFunc(func(s *spec) {
				s.flags |= flagDefaultValString | flagDefaultVal
				s.defaultValS = val
			})
		case "optional":
			if f[1] != "" {
				err = errors.New("optional does not take any arguments")
			}
			opt = Optional
		}
		if err != nil {
			return nil, err
		}
		if opt == nil {
			return nil, errors.New("unknown")
		}
		opt.modify(s)
		opt.modifyIPParser(p)
	}

	for _, opt := range opts {
		opt.modify(s)
		opt.modifyIPParser(p)
	}

	if s.flags&flagDefaultValString > 0 {
		if s.defaultVal, err = p.parse(s.defaultValS); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type ipParser struct {
}

func (p *ipParser) parse(s string) (interface{}, error) {
	return parseIP(
		s,
	)
}

func (p *ipParser) describe() interface{} {
	return struct{}{}
}
