package envcfg

// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.

import (
	"encoding/json"
	"errors"
	"strings"
)

// StringSlice extracts and parses a []string variable using the options provided.
//
// The first argument must be a string with beginning with the variable name as expected in the process environment.
// Any other options -- none of which are required -- may either be specified in the remainder of the string or using
// the type-safe StringSliceOpts.
//
// Available options:
// 		- "comma" or StringSliceComma
// 		- "default" or StringSliceDefault
// 		- "optional" or Optional
func (c *Cfg) StringSlice(docOpts string, opts ...StringSliceOpt) (v []string) {
	s, err := newStringSliceSpec(docOpts, opts)
	if err != nil {
		if c.panic {
			panic(err)
		}
		c.addError(err)
		return
	}
	c.addDescription(s.describe())
	v, _ = c.evaluate(s).([]string)
	return
}

// StringSliceOpt modifies StringSlice variable configuration.
type StringSliceOpt interface {
	modify(s *spec)
	modifyStringSliceParser(p *stringSliceParser)
}

// StringSliceComma specifies the comma to use for a StringSlice variable.
func StringSliceComma(comma rune) StringSliceOpt {
	return stringSliceOptFunc(func(p *stringSliceParser) {
		p.comma = comma
	})
}

// StringSliceDefault specifies a default value for a StringSlice variable.
func StringSliceDefault(def []string) StringSliceOpt {
	return defaultOpt(def)
}

type stringSliceOptFunc func(p *stringSliceParser)

func (f stringSliceOptFunc) modifyStringSliceParser(p *stringSliceParser) {
	f(p)
}

func (stringSliceOptFunc) modify(*spec) {}

var _ StringSliceOpt = new(stringSliceOptFunc)

func newStringSliceSpec(docOpts string, opts []StringSliceOpt) (*spec, error) {
	parsed, err := parse(docOpts)
	if err != nil {
		return nil, err
	}

	p := new(stringSliceParser)
	s := &spec{
		parser:   p,
		typeName: "[]string",
		name:     parsed.name,
		comment:  parsed.description,
	}

	for _, f := range parsed.fields {
		var (
			opt StringSliceOpt
			err error
		)
		switch strings.ToLower(f[0]) {
		case "comma":
			value := []rune(f[1])
			if len(value) != 1 {
				err = errors.New("must be only one rune")
				break
			}
			opt = StringSliceComma(value[0])
		case "default":
			val := f[1]
			opt = uniOptFunc(func(s *spec) {
				s.flags |= flagDefaultValString | flagDefaultVal
				s.defaultValS = val
			})
		case "optional":
			if f[1] != "" {
				err = errors.New("optional does not take any arguments")
			}
			opt = Optional
		}
		if err != nil {
			return nil, err
		}
		if opt == nil {
			return nil, errors.New("unknown")
		}
		opt.modify(s)
		opt.modifyStringSliceParser(p)
	}

	for _, opt := range opts {
		opt.modify(s)
		opt.modifyStringSliceParser(p)
	}

	if s.flags&flagDefaultValString > 0 {
		if s.defaultVal, err = p.parse(s.defaultValS); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type stringSliceParser struct {
	comma rune
}

func (p *stringSliceParser) parse(s string) (interface{}, error) {
	return parseSlice(s, p.comma)

}

func (p *stringSliceParser) describe() interface{} {
	return stringSliceParserDescription{
		Comma: p.comma,
	}
}

type stringSliceParserDescription struct {
	Comma rune `json:"comma,omitempty"`
}

func (d stringSliceParserDescription) MarshalJSON() ([]byte, error) {
	var comma string
	if d.Comma != 0 {
		comma = string(d.Comma)
	}
	return json.Marshal(struct {
		Comma string `json:"comma,omitempty"`
	}{
		Comma: comma,
	})
}
