package envcfg

// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.

import (
	"errors"
	"strconv"
	"strings"
)

// Uint extracts and parses a uint64 variable using the options provided.
//
// The first argument must be a string with beginning with the variable name as expected in the process environment.
// Any other options -- none of which are required -- may either be specified in the remainder of the string or using
// the type-safe UintOpts.
//
// Available options:
// 		- "base" or UintBase
// 		- "bit_size" or UintBitSize
// 		- "default" or UintDefault
// 		- "optional" or Optional
func (c *Cfg) Uint(docOpts string, opts ...UintOpt) (v uint64) {
	s, err := newUintSpec(docOpts, opts)
	if err != nil {
		if c.panic {
			panic(err)
		}
		c.addError(err)
		return
	}
	c.addDescription(s.describe())
	v, _ = c.evaluate(s).(uint64)
	return
}

// UintOpt modifies Uint variable configuration.
type UintOpt interface {
	modify(s *spec)
	modifyUintParser(p *uintParser)
}

// UintBase specifies the base to use for a Uint variable.
func UintBase(base int) UintOpt {
	return uintOptFunc(func(p *uintParser) {
		p.base = base
	})
}

// UintBitSize specifies the bit size to use for a Uint variable.
func UintBitSize(bitSize int) UintOpt {
	return uintOptFunc(func(p *uintParser) {
		p.bitSize = bitSize
	})
}

// UintDefault specifies a default value for a Uint variable.
func UintDefault(def uint64) UintOpt {
	return defaultOpt(def)
}

type uintOptFunc func(p *uintParser)

func (f uintOptFunc) modifyUintParser(p *uintParser) {
	f(p)
}

func (uintOptFunc) modify(*spec) {}

var _ UintOpt = new(uintOptFunc)

func newUintSpec(docOpts string, opts []UintOpt) (*spec, error) {
	parsed, err := parse(docOpts)
	if err != nil {
		return nil, err
	}

	p := new(uintParser)
	s := &spec{
		parser:   p,
		typeName: "uint64",
		name:     parsed.name,
		comment:  parsed.description,
	}

	for _, f := range parsed.fields {
		var (
			opt UintOpt
			err error
		)
		switch strings.ToLower(f[0]) {
		case "base":
			var val int
			val, err = strconv.Atoi(f[1])
			opt = UintBase(val)
		case "bit_size":
			var val int
			val, err = strconv.Atoi(f[1])
			opt = UintBitSize(val)
		case "default":
			val := f[1]
			opt = uniOptFunc(func(s *spec) {
				s.flags |= flagDefaultValString | flagDefaultVal
				s.defaultValS = val
			})
		case "optional":
			if f[1] != "" {
				err = errors.New("optional does not take any arguments")
			}
			opt = Optional
		}
		if err != nil {
			return nil, err
		}
		if opt == nil {
			return nil, errors.New("unknown")
		}
		opt.modify(s)
		opt.modifyUintParser(p)
	}

	for _, opt := range opts {
		opt.modify(s)
		opt.modifyUintParser(p)
	}

	if s.flags&flagDefaultValString > 0 {
		if s.defaultVal, err = p.parse(s.defaultValS); err != nil {
			return nil, err
		}
	}

	return s, nil
}

type uintParser struct {
	base    int
	bitSize int
}

func (p *uintParser) parse(s string) (interface{}, error) {
	return strconv.ParseUint(
		s,
		p.base,
		p.bitSize,
	)
}

func (p *uintParser) describe() interface{} {
	return uintParserDescription{
		Base:    p.base,
		BitSize: p.bitSize,
	}
}

type uintParserDescription struct {
	Base    int `json:"base,omitempty"`
	BitSize int `json:"bit_size,omitempty"`
}
