// Code generated by internal/cmd/gen/gen.go DO NOT EDIT.
package envcfg

type UniOpt interface {
	modify(s *spec)
	modifyBoolParser(p *boolParser)
	modifyBytesParser(p *bytesParser)
	modifyDurationParser(p *durationParser)
	modifyFloatParser(p *floatParser)
	modifyIntParser(p *intParser)
	modifyIntSliceParser(p *intSliceParser)
	modifyStringParser(p *stringParser)
	modifyStringSliceParser(p *stringSliceParser)
	modifyTimeParser(p *timeParser)
	modifyUintParser(p *uintParser)
}

type uniOptFunc func(s *spec)

func (f uniOptFunc) modify(s *spec) {
	f(s)
}

func (uniOptFunc) modifyBoolParser(p *boolParser) {}

func (uniOptFunc) modifyBytesParser(p *bytesParser) {}

func (uniOptFunc) modifyDurationParser(p *durationParser) {}

func (uniOptFunc) modifyFloatParser(p *floatParser) {}

func (uniOptFunc) modifyIntParser(p *intParser) {}

func (uniOptFunc) modifyIntSliceParser(p *intSliceParser) {}

func (uniOptFunc) modifyStringParser(p *stringParser) {}

func (uniOptFunc) modifyStringSliceParser(p *stringSliceParser) {}

func (uniOptFunc) modifyTimeParser(p *timeParser) {}

func (uniOptFunc) modifyUintParser(p *uintParser) {}

var _ UniOpt = new(uniOptFunc)
